name: Run Gradle on main

on:
  push:
    branches: [ "main" ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Execute Gradle build
      run: ./gradlew build --info --build-cache
